apiVersion: skaffold/v4beta6
kind: Config
build:
  artifacts:
    - image: sayantan16/blog_client
      context: client
      sync:
        manual:
          - src: "src/**/*.js"
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: sayantan16/blog_comments
      context: comments
      sync:
        manual:
          - src: "*.js"
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: sayantan16/blog_eventbus
      context: event-bus
      sync:
        manual:
          - src: "*.js"
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: sayantan16/blog_moderation
      context: moderation
      sync:
        manual:
          - src: "*.js"
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: sayantan16/blog_posts
      context: posts
      sync:
        manual:
          - src: "*.js"
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: sayantan16/blog_query
      context: query
      sync:
        manual:
          - src: "*.js"
            dest: .
      docker:
        dockerfile: Dockerfile
  local:
    push: false
manifests:
  rawYaml:
    - ./infra/k8s/*
deploy:
  kubectl: {}
